CREATE DATABASE IF NOT EXISTS BD_APLICATIVO_MUSICA;
USE BD_APLICATIVO_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    CAPA BLOB NOT NULL,
    DESCRICAO VARCHAR(255),
    FK_CPF_ARTISTA VARCHAR(20),
    FOREIGN KEY (FK_CPF_ARTISTA) REFERENCES ARTISTA (CPF)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    LETRA VARCHAR(620) NOT NULL,
    DATA_POST DATE NOT NULL,
    FOTO BLOB NOT NULL,
    FK_ID_GENERO INTEGER,
    FK_ID_ALBUM INTEGER,
    FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO (ID),
    FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM (ID)
);
