CREATE DATABASE IF NOT EXISTS BD_BIBLIOTECA;
USE BD_BIBLIOTECA;

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    FOTO BLOB
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    GENERO VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255),
    FK_CPF_AUTOR VARCHAR(15),
    FOREIGN KEY (FK_CPF_AUTOR) REFERENCES AUTOR (CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO_AUTOR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_LIVRO_DIGITAL INTEGER,
    FK_CPF_LEITOR VARCHAR(15),
    FOREIGN KEY (FK_ID_LIVRO_DIGITAL) REFERENCES LIVRO_DIGITAL (ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_LEITOR) REFERENCES LEITOR (CPF) ON DELETE CASCADE
);