CREATE DATABASE IF NOT EXISTS BD_ENQUETES;
USE BD_ENQUETES;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR(255) NOT NULL UNIQUE,
    USU_AREA_ATUACAO VARCHAR(500),
    USU_PROFISSAO VARCHAR(200),
    USU_AREA_FORMACAO VARCHAR(500),
    USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO","CASADO","DIVORCIADO","VIÚVO") NOT NULL,
    USU_ESTADO VARCHAR(2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL","MÉDIO","SUPERIOR") NOT NULL,
    USU_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY (USU_CODIGO)
);

CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
    ENQ_DATA_FINAL DATE NOT NULL,
    ENQ_DATA_INICIAL DATE NOT NULL,
    ENQ_DESCRICAO VARCHAR(500) NOT NULL,
    ENQ_NOME VARCHAR(255) NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (ENQ_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO (USU_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	URE_CODIGO INTEGER AUTO_INCREMENT,
    URE_DATA DATE NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (URE_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO (USU_CODIGO) ON DELETE CASCADE,
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE (ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PER_DESCRICAO VARCHAR(500) NOT NULL UNIQUE,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (PER_CODIGO),
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE (ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT,
    RES_DESCRICAO VARCHAR(500) NOT NULL UNIQUE,
    RES_CERTA VARCHAR(1) NOT NULL,
    FK_PER_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (RES_CODIGO),
    FOREIGN KEY (FK_PER_CODIGO) REFERENCES PERGUNTAS (PER_CODIGO) ON DELETE CASCADE
);

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO , USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO,USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUES ( "2025-10-06", "maria.silva","TI","Desenvolvedora de sistemas", "Tecnologia da Informação","2000-02-10", "SOLTEIRO","SP","SUPERIOR","maria.silva@exemplo.com"," M$lva2025!","Maria Eduarda");

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO , USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO,USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUES ( "2025-11-08", "lucas.jose","ADM","Administrador", "administração","1998-03-19", "SOLTEIRO","MG","SUPERIOR","lucas.tech@exemplo.com"," T3ch!Luca$#9","Lucas José");

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO , USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO,USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUES ( "2025-12-20", "paula.fernandes","MKT","desings", "designs","1988-07-30", "CASADO","AM","SUPERIOR","paula.admin@exemplo.com","  Adm!nP@u1a25","Paula Fernandes");


SELECT * FROM USUARIO;

INSERT INTO ENQUETE (ENQ_DATA_FINAL,ENQ_DATA_INICIAL ,ENQ_DESCRICAO,ENQ_NOME, FK_USU_CODIGO )
VALUES ( "2026-02-04", "2025-10-09","Identifica qual área da TI mais desperta interesse, revelando preferências de carreira e estudo.","Tecnologia", 1);

INSERT INTO ENQUETE (ENQ_DATA_FINAL,ENQ_DATA_INICIAL ,ENQ_DESCRICAO,ENQ_NOME ,FK_USU_CODIGO)
VALUES ( "2026-08-06", "2025-10-23","Aponta quais áreas de formação são mais atraentes para quem busca novas oportunidades profissionais.","Educação e Carreira",2);

INSERT INTO ENQUETE (ENQ_DATA_FINAL,ENQ_DATA_INICIAL ,ENQ_DESCRICAO,ENQ_NOME ,FK_USU_CODIGO)
VALUES ( "2026-11-25", "2025-12-30","Mostra quais ferramentas digitais fazem mais parte da rotina das pessoas.","Cotidiano",3);


SELECT * FROM USUARIO_RESPONDE_ENQUETE;

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA ,FK_USU_CODIGO,FK_ENQ_CODIGO )
VALUES( "2026-01-09", "1", "1");

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA ,FK_USU_CODIGO,FK_ENQ_CODIGO )
VALUES( "2026-03-22", "2", "2");

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA ,FK_USU_CODIGO,FK_ENQ_CODIGO )
VALUES( "2026-09-18", "3", "3");


SELECT * FROM PERGUNTAS;

INSERT INTO PERGUNTAS (PER_DESCRICAO ,FK_ENQ_CODIGO)
VALUES("Qual área da TI mais chama sua atenção?","1");

INSERT INTO PERGUNTAS (PER_DESCRICAO ,FK_ENQ_CODIGO)
VALUES("Se pudesse escolher uma nova formação, qual seria?","2");

INSERT INTO PERGUNTAS (PER_DESCRICAO ,FK_ENQ_CODIGO)
VALUES("Qual ferramenta você mais usa no dia a dia?","3");

SELECT * FROM RESPOSTAS;

INSERT INTO RESPOSTAS ( RES_DESCRICAO,RES_CERTA,FK_PER_CODIGO )
VALUES("A-Desenvolvimento","B","1");

INSERT INTO RESPOSTAS ( RES_DESCRICAO,RES_CERTA,FK_PER_CODIGO )
VALUES("B-Segurança da Informação","B","1");

INSERT INTO RESPOSTAS ( RES_DESCRICAO,RES_CERTA,FK_PER_CODIGO )
VALUES("C-Inteligência Artificial","B","1");









