CREATE DATABASE IF NOT EXISTS BD_GESTAO_ESTOQUE;
USE BD_GESTAO_ESTOQUE;

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(20) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    PESO VARCHAR(10) NOT NULL,
    VALIDADE DATE,
    FK_ID_CATEGORIA INTEGER,
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FOR_PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CNPJ_FORNECEDOR VARCHAR(20),
    FK_ID_PRODUTO INTEGER,
    FOREIGN KEY (FK_CNPJ_FORNECEDOR) REFERENCES FORNECEDOR (CNPJ) ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_PRODUTO) REFERENCES PRODUTO (ID) ON DELETE CASCADE
);