CREATE DATABASE IF NOT EXISTS BD_HOTEL;
USE BD_HOTEL;

CREATE TABLE IF NOT EXISTS HOTEL(
	CNPJ VARCHAR(20) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS HOSPEDE(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS QUARTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NUMERO INTEGER NOT NULL,
    FOTO BLOB,
    FK_CNPJ_HOTEL VARCHAR(20),
    FOREIGN KEY (FK_CNPJ_HOTEL) REFERENCES HOTEL (CNPJ) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTO_HOSPEDE(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_QUARTO INTEGER,
    FK_CPF_HOSPEDE VARCHAR(15),
    FOREIGN KEY (FK_ID_QUARTO) REFERENCES QUARTO (ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_HOSPEDE) REFERENCES HOSPEDE (CPF) ON DELETE CASCADE
);