CREATE DATABASE IF NOT EXISTS BD_MEDICO;
USE BD_MEDICO;

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    ESPECIALIZACAO VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR(15) PRIMARY KEY,
    TELEFONE VARCHAR(15) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    HORA VARCHAR(4) NOT NULL,
    SENHA VARCHAR(10) NOT NULL,
    FK_MEDICO_CRM VARCHAR(20),
    FK_PACIENTE_CPF VARCHAR(15),
    FOREIGN KEY (FK_MEDICO_CRM) REFERENCES MEDICO (CRM) ON DELETE CASCADE,
    FOREIGN KEY (FK_PACIENTE_CPF) REFERENCES PACIENTE (CPF) ON DELETE CASCADE
);