CREATE DATABASE IF NOT EXISTS BD_PASSAGEM_AEREA;
USE BD_PASSAGEM_AEREA;

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(6) NOT NULL,
    RG VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSAPORTE VARCHAR (30) NOT NULL
);

CREATE TABLE IF NOT EXISTS VOO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL,
    DATA_HORA DATE NOT NULL,
    LOCAL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	NUMERO VARCHAR(5) PRIMARY KEY,
    CATEGORIA VARCHAR(5) NOT NULL,
    LOCAL_ASSENTO VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255),
    FK_ID_VOO INTEGER,
    FK_CPF_PASSAGEIRO VARCHAR(15),
    FOREIGN KEY (FK_ID_VOO) REFERENCES VOO (ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_PASSAGEIRO) REFERENCES PASSAGEIRO (CPF) ON DELETE CASCADE
);